# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: block-policy-v1-0-impl # This value will be overriden during 'make run' execution
        namespace: default
      # Fill the config with a policy configuration that matches the schema specified in the policy
      # definition gcl.yaml. Eg:
      # config:
      #   someProperty: desiredValue
      config:
        source: https://block-ips-ldb70c.cio5fo.usa-e1.cloudhub.io/ips
        frequency: 60
